<?php
   include("config.php");
   session_start();
   //unset($_SESSION["Id"]);
   //unset($_SESSION["username"]);
   session_unset();
   session_destroy();
   header("Location:index.php");
?>